### ISSUE TITLE
How to use with Preact or transform JSX by hand?

### ISSUE THREAD

**Issue by jcubic** [Thor-x86/compodraw-js#1]
I would like to use the library with JSX but not with React is there a way to define my own pragma or there is only hardcoded `React.createElement`?

I would like to use it with my Scheme interpreter where I use SXML but I need to specify the pragma myself. I use `h` by default like in Preact.

**Comment by Thor-x86** [comment]
CompoDraw is independent from React and you don't have to use `React.createElement`. The most important thing is **canvas element**, no matter where it came from.

Despite of not having React, if you did figured out how to use JSX without React, then it should works. As alternative, you can use plain string with XML formatted.

If you're clear, let me close the comment for you.

**Comment by jcubic** [comment]
Do you have example how to use the library without JSX but with JSX pragma?

**Comment by jcubic** [comment]
With react you don't need to use JSX you can write the code in JavaScript by hand and it should work. But I have no idea how this should work with your library.

**Comment by Thor-x86** [comment]
Doing JSX by hand without its syntax just going to be pointless. Instead, why not compose it directly?

Example: https://github.com/Thor-x86/compodraw-js/blob/dev/examples/usage-programmatical.md

**Comment by jcubic** [comment]
It's not pointless, as I've said I use SXML (standard way of wrinting XML in lisp, which you is similar to JSX), but I need to know how the internals works. I prefer declarative style, with imperative code, I can have the same with normal canvas object, I don't need your library to make things more complicated that it is.

**Comment by jcubic** [comment]
Do you have examples online that prove that your library actually works?
I've created basic example with Preact https://codepen.io/jcubic/pen/mdOgMQQ?editors=0010
but got error `"rectangle" is not registered in 'withInstructs' at composeFromJsx(jsx, withInstructs) function`
